version: 2.1
orbs: 
  sonarcloud: sonarsource/sonarcloud@1.1.1

jobs:
  build_backend:
    working_directory: /DeployTestISA
    steps:
      - checkout
      - run: cd SpringProject
      - run: ls -l
      - run:
          name: Build
          command: cd SpringProject && mvn verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=mrsisatim20
  deploy_backend:
     steps:
       - checkout
       - run:
            name: Deploy backend
            command: git subtree push --prefix SpringProject https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master
  build_frontend:
    working_directory: ~/DeployTestISA
    steps:
      - checkout
      - run: cd VueProject/isa-mrs-front
      - run: ls -l 
      - run:
          name: update-npm
          command: "sudo npm install -g npm@5"
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: install-packages
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
          - ./node_modules
  deploy_frontend:
    steps:
       - checkout
       - run:
            name: Deploy VueProject
            command: git subtree push --prefix VueProject/isa-mrs-front https://heroku:$HEROKU_API_KEY@git.heroku.com/test-rivera-frontend.git master
  
workflows:
  sample:
    jobs:
      - build_backend
      - deploy_backend
      - build_frontend
      - deploy_frontend